name: Deploy Jekyll with GitHub Pages dependencies pre-staged

on:
  push:
    branches: ["main"] # Cambia 'main' por el nombre de tu rama principal si es diferente

  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permite que el flujo de trabajo lea el contenido del repositorio y despliegue en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Solo se permite un despliegue concurrente, saltándose los pre-ejecutados que estén en cola entre el actual y el último
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Trabajo de compilación (build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3

  # Trabajo de despliegue (deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
